<?php

// $Id$

/**
 * @file
 *
 * Implements hooks and callbacks for this module.
 */

/**
 * Executes the given command and the exit status and output of the command.
 * 
 * @param string $command
 *   The command to execute.
 * 
 * @return array
 *   Where the first parameter was the exit status of the command and the second is the commands output.
 */
function bibutils_execute_command($command) {
  $return_value = FALSE;
  ob_start();
  passthru($command, $return_value);
  $output = ob_get_contents();
  ob_end_clean();
  return array($return_value, $output);
}

/**
 * An internal function that is not meant to be used outside of this file.
 * 
 * This function does the nuts and the bolts of the mods conversion.
 * 
 * @param string $command
 *   The command expected to return a MODS string to the standard output.
 * 
 * @return DOMDocument
 *   The generated MODS document, FALSE if the function failed.
 */
function _bibutils_convert_to_mods($command) {
  list($return_value, $output) = bibutils_execute_command($command);
  $successful = $return_value === 0;
  if ($successful && !empty($output)) { // Successfully executed the command.
    $doc = new DOMDocument();
    $doc->loadXML($output);
    return $doc;
  }
  else {
    drupal_set_message(t('Could not convert %filename, to MODS.', array('%filename' => $filename)), 'error');
  }
  return FALSE;
}

/**
 * Converts an Endnote XML document to a MODS document.
 * 
 * @param string $filename
 *   The filename of the EndNote XML document.
 * 
 * @return DOMDocument
 *   The generated MODS document, FALSE if the function failed.
 */
function bibutils_endnote_xml_file_to_mods_file($filename) {
  $command = 'endx2xml ' . $filename;
  return _bibutils_convert_to_mods($command);
}

/**
 * Converts an RIS document to a MODS document.
 * 
 * @param string $filename
 *   The filename of the RIS.
 * 
 * @return DOMDocument
 *   The generated MODS document, FALSE if the function failed.
 */
function bibutils_ris_file_to_mods_file($filename) {
  $command = 'ris2xml ' . $filename;
  return _bibutils_convert_to_mods($command);
}