<?php

/**
 * @file
 *
 * Citation Class.
 */

// 

/*drupal_add_js(array(
    'ir_citation' => array(
      'abbreviations' => array(
        $name => array(
          $var_type => $abbreviation_data,
        )
      )
    )), 'setting');
*/
class CiteProcCitationManager {
  
}

// 
class CiteProcCSLStyle {
  
}

// Create one or more abbreviations
class CiteProcAbbreviation {
  
}

// Create one or more abbreviations
class CiteProcCitation {
  
}