<?php

/**
 * @file
 *
 * Implements hooks and callbacks for this module.
 */
/**
 * Constants Permission/Menu/Theme
 */
define('MENU_BIBLIOGRAPHY_HOME', 'bibliography');
define('MENU_BIBLIOGRAPHY_CITATION', 'bibliography/citation');
define('MENU_BIBLIOGRAPHY_EXPORT', 'bibliography/export');
define('THEME_BIBLIOGRAPHY_FORM_TABLE', 'islandora_bibliography_form_table');

/**
 * The menu entries for this module.
 *
 * @return $menu_entries
 *   An arrray of the items to be added to the drupal menu
 */
function islandora_bibliography_menu() {
  $items = array();
  $items[MENU_BIBLIOGRAPHY_HOME] = array(
    'title' => 'My Bibliography',
    'description' => 'Here you can remove or export citations from your bibliography.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_bibliography_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items[MENU_BIBLIOGRAPHY_CITATION] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_bibliography_citation_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items[MENU_BIBLIOGRAPHY_EXPORT] = array(
    'page callback' => 'islandora_bibliography_export',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme().
 *
 */
function islandora_bibliography_theme() {
  return array(
    THEME_BIBLIOGRAPHY_FORM_TABLE => array(
      'arguments' => array('element' => NULL)
    )
  );
}

/**
 * Export many citations in a particular format and redirect the user to another page.
 */
function islandora_bibliography_export() {
  $export = isset($_SESSION['bibliography']['export']) ? $_SESSION['bibliography']['export'] : NULL;
  $filename = isset($export['filename']) ? $export['filename'] : NULL;
  $mime_type = isset($export['mime_type']) ? $export['mime_type'] : NULL;
  $download_filename = isset($export['download_filename']) ? $export['download_filename'] : $filename;
  $redirect = isset($export['redirect']) ? $export['redirect'] : NULL;
  unset($_SESSION['bibliography']['export']);
  if (file_exists($filename)) {
    $file_size = filesize($filename);
    header("Content-type: $mime_type");
    header("Content-length: $file_size");
    header("Content-Disposition: attachment; filename=\"$download_filename\"");
    header("Cache-control: private");
    $curl_handle = curl_init();
    if ($curl_handle !== FALSE) {
      global $base_url;
      $url = $base_url . '/' . $filename;
      curl_setopt($curl_handle, CURLOPT_SSL_VERIFYPEER, FALSE);
      curl_setopt($curl_handle, CURLOPT_SSL_VERIFYHOST, FALSE);
      curl_setopt($curl_handle, CURLOPT_FAILONERROR, 1); // Fail on errors
      curl_setopt($curl_handle, CURLOPT_FOLLOWLOCATION, 1); // allow redirects
      curl_setopt($curl_handle, CURLOPT_USERAGENT, "Mozilla/4.0 pp(compatible; MSIE 5.01; Windows NT 5.0)");
      curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 0); // return into a variable
      curl_setopt($curl_handle, CURLOPT_URL, $url);
    }
    curl_exec($curl_handle);
    curl_close($curl_handle);
  }
  else {
    drupal_goto($redirect);
    exit();
  }
}

/**
 * This form is called from the menu callback for the 'My Bibliography' page.
 *
 * From here the user can add/remove and export citations.
 *
 * @global string $base_path
 *   The base path of the site.
 *
 * @param array $form_state
 *   The drupal form state.
 *
 * @return array
 *   The drupal form.
 */
function islandora_bibliography_form(array &$form_state) {
  global $base_path;
  drupal_add_css(drupal_get_path('module', 'islandora_bibliography') . '/css/bibliography.css');
  if (isset($_SESSION['bibliography']['export'])) {
    $path = MENU_BIBLIOGRAPHY_EXPORT;
    drupal_set_html_head("<meta http-equiv='refresh' content='0;url=/$path'/>");
  }
  module_load_include('inc', 'islandora_bibliography', 'Bibliography');
  $pids = Bibliography::GetCitations();
  if (empty($pids)) {
    drupal_set_message(t('You have no citations in your bibliography.'));
    return array(
      'redirect' => array(
        '#prefix' => '<p>',
        '#value' => l(t('Return to the Home Page.'), ''),
        '#suffix' => '</p>'
      )
    );
  }
  else {
    module_load_include('inc', 'fedora_repository', 'api/fedora_item');
    $checkboxes = array_fill_keys($pids, '');
    $table = array(
      '#header' => array(theme('table_select_header_cell'), t('Title'), t('Author(s)'), ''),
      '#theme' => THEME_BIBLIOGRAPHY_FORM_TABLE,
      '#tree' => TRUE,
      'selections' => array(
        '#type' => 'checkboxes',
        '#options' => $checkboxes,
      ),
    );
    foreach ($pids as $pid) {
      $title = $authors = 'Missing';
      $item = new Fedora_Item($pid);
      if (isset($item->datastreams['MODS'])) {
        $mods = $item->get_datastream_dissemination('MODS');
        $mods = trim($mods);
        if (!empty($mods)) {
          $mods = new SimpleXMLElement($mods);
          $mods->registerXPathNamespace('mods', 'http://www.loc.gov/mods/v3');
          $title = implode(' ', $mods->xpath('/mods:mods/mods:titleInfo/mods:title'));
          $authors = implode(' ', $mods->xpath('/mods:mods/mods:name/mods:role[mods:roleTerm = "author"]/../mods:namePart[@type="family"]'));
        }
      }
      $table['rows'][] = array(
        '#pid' => $pid,
        'title' => array('#value' => check_plain($pid)),
        'author' => array('#value' => check_plain($authors)),
        'remove' => array(
          '#type' => 'submit',
          '#value' => t('Remove'),
          '#pid' => $pid,
          '#submit' => array('islandora_bibliography_form_remove_citation_submit')
        )
      );
    }
    module_load_include('inc', 'csl', 'CSL');
    $styles = CSL::GetNames();
    return array(
      'fieldset' => array(
        '#type' => 'fieldset',
        '#title' => t('My Citations'),
        '#description' => t('<p>Here you can remove or export citations from your bibliography.</p>'),
        'table' => $table,
        'preview_title' => array(
          '#value' => t('Preview Citations'),
          '#prefix' => '<h4>',
          '#suffix' => '</h4>'
        ),
        'preview_style' => array(
          '#title' => t('Style'),
          '#type' => 'select',
          '#options' => $styles
        ),
        'preview' => array(
          '#type' => 'submit',
          '#value' => t('Preview Selected'),
          '#submit' => array('islandora_bibliography_form_preview')
        ),
        'remove' => array(
          '#type' => 'submit',
          '#value' => t('Remove Selected'),
          '#submit' => array('islandora_bibliography_form_remove')
        ),
        'export_title' => array(
          '#value' => t('Export To File'),
          '#prefix' => '<h4>',
          '#suffix' => '</h4>'
        ),
        'format' => array(
          '#title' => t('Format'),
          '#type' => 'select',
          '#length' => 50,
          '#options' => array(
            'RIS' => 'RIS',
            'RTF' => 'RTF',
            'PDF' => 'PDF',
          )
        ),
        'style' => array(
          '#title' => t('Style'),
          '#type' => 'select',
          '#options' => $styles
        ),
        'export' => array(
          '#type' => 'submit',
          '#action' => 'export',
          '#export' => 'selected',
          '#value' => t('Export Selected'),
          '#submit' => array('islandora_bibliography_form_export')
        )
      )
    );
  }
}

/**
 * Removes one citation from the bibliography.
 *
 * @param array $form
 *   The drupal form.
 * @param array $form_state
 *   The drupal form state.
 */
function islandora_bibliography_form_remove_citation_submit(array $form, array &$form_state) {
  module_load_include('inc', 'islandora_bibliography', 'Bibliography');
  $pid = $form_state['clicked_button']['#pid'];
  Bibliography::RemoveCitation($pid);
  drupal_set_message(t('Removed Citation'));
}

/**
 * Previews the selected citations from the bibliography.
 *
 * @param array $form
 *   The drupal form.
 * @param array $form_state
 *   The drupal form state.
 */
function islandora_bibliography_form_preview(array $form, array &$form_state) {
  $selections = $form_state['values']['table']['selections'];
  _islandora_bibliography_form_preview_selections($selections, $form_state['values']['preview_style']);
}

/**
 * Removes the selected citations from the bibliography.
 *
 * @param array $form
 * @param array $form_state
 */
function islandora_bibliography_form_remove(array $form, array &$form_state) {
  module_load_include('inc', 'islandora_bibliography', 'Bibliography');
  $selections = array_filter($form_state['values']['table']['selections']);
  $pids = array_keys($selections);
  Bibliography::RemoveCitations($pids);
  drupal_set_message(t('Removed %num Citation(s)', array('%num' => count($pids))));
}

/**
 * Exports the selected pids to file.
 *
 * @param array $form
 * @param array $form_state
 */
function islandora_bibliography_form_export(array $form, array &$form_state) {
  $selections = array_filter($form_state['values']['table']['selections']);
  $pids = array_keys($selections);
  islandora_bibliography_export_citations($pids, $form_state['values']['style'], $form_state['values']['format']);
}

/**
 * Export the users selections.
 *
 * Helper function for islandora_bibliography_form_submit().
 *
 * @param array $selections
 *   The users selections, the keys are pids and the values indicated if it was selected.
 * @param string $style
 *   The name of the style file to use.
 */
function _islandora_bibliography_form_preview_selections(array $selections, $style) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  module_load_include('inc', 'citeproc', 'CiteProcJSBibliography');
  drupal_add_css(drupal_get_path('module', 'islandora_bibliography') . '/css/export.css');
  $style = citeproc_style($style);
  $bibliography = new CiteProcJSBibliography($style);
  $selections = array_filter($selections);
  foreach ($selections as $pid => $selected) {
    $item = new Fedora_Item($pid);
    if (isset($item->datastreams['MODS'])) {
      $mods = trim($item->get_datastream_dissemination('MODS'));
      if (!empty($mods)) {
        $doc = new DOMDocument();
        $doc->loadXML($mods);
        $citation = citeproc_citation_from_mods($doc);
        $bibliography->addCitation($citation);
      }
    }
  }
  $output = $bibliography->render();
  $output .= l(t('Return to the Bibliography.'), 'bibliography');
  print theme('page', $output, FALSE);
  exit();
}

/**
 * Theme's a form table for this module.
 *
 * @param array $element
 *   A Drupal Form Element.
 *
 * @return sting
 *   HTML that renders a table of settings for datastreams.
 */
function theme_islandora_bibliography_form_table(array $element) {
  $rows = array();
  foreach (element_children($element['rows']) as $child) {
    $setting = $element['rows'][$child];
    $pid = $setting['#pid'];
    $fields = array(
      drupal_render($element['selections'][$pid]) // First field is a checkbox
    );
    foreach (element_children($setting) as $property) {
      $field = $setting[$property];
      $fields[] = drupal_render($field);
    }
    $rows[] = array(
      'data' => $fields,
      'class' => isset($setting['#attributes']['class']) ? $setting['#attributes']['class'] : NULL
    );
  }
  $attributes = isset($element['#id']) ? array('id' => $element['#id']) : NULL;
  return theme_table($element['#header'], $rows, $attributes);
}

/**
 * Renders the form for adding/removing an item from the bibliography.
 *
 * @param array $form_state
 *   The drupal form state.
 * @param string $pid
 *   The fedora object's pid.
 *
 * @return array
 *   The drupal form.
 */
function islandora_bibliography_citation_form(array &$form_state, $pid = NULL) {
  module_load_include('inc', 'islandora_bibliography', 'Bibliography');
  $pid = isset($pid) ? $pid : $form_state['post']['pid'];
  $stored = isset($form_state['post']['stored']) ? $form_state['post']['stored'] : Bibliography::Exists($pid);
  return array(
    '#action' => '/bibliography/citation',
    'pid' => array(
      '#type' => 'hidden',
      '#value' => $pid
    ),
    'stored' => array(
      '#type' => 'hidden',
      '#value' => $stored
    ),
    'action' => array(
      '#type' => 'submit',
      '#value' => $stored ? t('Remove from Bibliography') : t('Add to Bibliography'),
      '#action' => $stored ? 'remove' : 'add',
      '#pid' => $pid,
      '#redirect' => 'fedora/repository/' . $pid,
    )
  );
}

/**
 * Adds/Removes a Citation from the bibliography.
 *
 * @param array $form
 *   The drupal form.
 * @param array $form_state
 *   The drupal form state.
 */
function islandora_bibliography_citation_form_submit(array $form, array &$form_state) {
  module_load_include('inc', 'islandora_bibliography', 'Bibliography');
  $action = $form_state['clicked_button']['#action'];
  $pid = $form_state['clicked_button']['#pid'];
  ($action == 'add') ?
          Bibliography::AddCitation($pid) :
          Bibliography::RemoveCitation($pid);
  $redirect = $form_state['clicked_button']['#redirect'];
  drupal_goto($redirect);
}

/**
 *
 * @param array $pids
 * @param array $context
 */
function _islandora_bibliography_batch_combine_mods($filename, $pid, array &$context) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $mods = new DOMDocument();
  $mods->load($filename);
  $item = new Fedora_Item($pid);
  if ($item->exists() && isset($item->datastreams['MODS'])) {
    $datastream = $item->get_datastream_dissemination('MODS');
    $datastream = trim($datastream);
    if (!empty($mods)) {
      $doc = new DOMDocument();
      $doc->loadXML($datastream);
      $node = $mods->importNode($doc->documentElement, TRUE);
      $mods->documentElement->appendChild($node);
      $mods->save($filename);
    }
  }
}

/**
 *
 * @param array $pids
 * @param string $redirect
 * @param array $context
 */
function _islandora_bibliography_convert_mods_to_ris($filename, array &$context) {
  $context['results']['filename'] = bibutils_mods_file_to_ris_document($filename);
  $context['results']['mime_type'] = 'application/x-Research-Info-Systems';
  $context['results']['download_filename'] = 'export.ris';
}

/**
 *
 * @param type $redirect
 * @param array $context
 */
function _islandora_bibliography_redirect($redirect, array &$context) {
  $context['results']['redirect'] = $redirect;
}

/**
 *
 * @param type $pid
 */
function _islandora_bibliography_batch_convert_mods_to_json($pid, array &$context) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  module_load_include('php', 'citeproc', 'generators/converter');
  $item = new Fedora_Item($pid);
  if ($item->exists() && isset($item->datastreams['MODS'])) {
    $mods = $item->get_datastream_dissemination('MODS');
    $mods = trim($mods);
    if (!empty($mods)) {
      $context['results']['data'][] = convert_mods_to_citeproc_jsons($mods);
    }
  }
}

function _islandora_bibliography_convert_json_to_rtf($style, array &$context) {
  module_load_include('php', 'islandora_bibliography', 'class_rtf');
  module_load_include('php', 'CiteProc', 'lib/citeproc-php/CiteProc');
  /* Style */
  $csl = new DomDocument();
  $csl->load(drupal_get_path('module', 'CiteProc') . '/data/' . $style);
  /* Citations */
  $citeproc = new citeproc($csl->saveXML());
  $rtf = new rtf();
  foreach ($context['results']['data'] as $citation) {
    $citation = (object) $citation;
    $citation = json_decode(json_encode($citation)); // HACKKKKK!
    $text = $citeproc->render($citation, 'bibliography');
    $rtf->addText($text . '<br/>');
  }
  /* File */
  $temp_file_dir = file_directory_temp();
  $temp_file_name = file_create_filename("export.rtf", $temp_file_dir);
  $file = fopen($temp_file_name, 'w');
  if ($file !== FALSE) {
    $document = $rtf->getDocument();
    fwrite($file, $document);
    fclose($file);
  }
  /* Batch Values */
  $context['results']['filename'] = $temp_file_name;
  $context['results']['download_filename'] = 'export.rtf';
  $context['results']['mime_type'] = 'application/rtf';
}

function _islandora_bibliography_convert_rtf_to_pdf(array &$context) {
  $output = array();
  $return_value = FALSE;
  $filename = $context['results']['filename'];
  exec('soffice.bin --headless -convert-to pdf ' . $filename, $output, $return_value);
  $filename = preg_replace('/\.rtf$/', '.pdf', $context['results']['filename']);
  $context['results']['filename'] = $filename;
  $context['results']['download_filename'] = 'export.pdf';
  $context['results']['mime_type'] = 'application/pdf';
}

/**
 *
 * @param boolean $successful
 * @param array $results
 * @param array $operations
 */
function _islandora_bibliography_export_citations($successful, array $results, array $operations) {
  $_SESSION['bibliography']['export']['filename'] = $results['filename'];
  $_SESSION['bibliography']['export']['download_filename'] = $results['download_filename'];
  $_SESSION['bibliography']['export']['mime_type'] = $results['mime_type'];
  $_SESSION['bibliography']['export']['redirect'] = $results['redirect'];
}

/**
 *
 * @param array $pids
 * @param type $style
 * @param string $file_format
 *   Either pdf, rtf, ris, if null display to screen.
 */
function islandora_bibliography_export_citations(array $pids, $style, $file_format = NULL) {
  $operations = array();
  switch ($file_format) {
    case 'RIS':
      $temp_file_dir = file_directory_temp();
      $temp_file = file_create_filename("mods.xml", $temp_file_dir);
      $mods = new DOMDocument();
      $mods->loadXML('<modsCollection xmlns="http://www.loc.gov/mods/v3" />');
      $mods->save($temp_file);
      foreach ($pids as $pid) {
        $operations[] = array('_islandora_bibliography_batch_combine_mods', array($temp_file, $pid));
      }
      $operations[] = array('_islandora_bibliography_convert_mods_to_ris', array($temp_file));
      $operations[] = array('_islandora_bibliography_redirect', array($_GET['q']));
      break;
    case 'RTF':
      foreach ($pids as $pid) {
        $operations[] = array('_islandora_bibliography_batch_convert_mods_to_json', array($pid));
      }
      $operations[] = array('_islandora_bibliography_convert_json_to_rtf', array($style));
      $operations[] = array('_islandora_bibliography_redirect', array($_GET['q']));
      break;
    case 'PDF':
      foreach ($pids as $pid) {
        $operations[] = array('_islandora_bibliography_batch_convert_mods_to_json', array($pid));
      }
      $operations[] = array('_islandora_bibliography_convert_json_to_rtf', array($style));
      $operations[] = array('_islandora_bibliography_convert_rtf_to_pdf', array());
      $operations[] = array('_islandora_bibliography_redirect', array($_GET['q']));
      break;
  }
  if (count($operations) > 0) {
    $batch = array(
      'title' => t('Exporting File'),
      'operations' => $operations,
      'finished' => '_islandora_bibliography_export_citations'
    );
    batch_set($batch);
  }
}